name_search="//input[@placeholder='Enter Name or Email']"
Birthday="(//input[@placeholder='Birthday'])[1]"
Birthday_box="(//span[normalize-space()='01'])[1]"
JoinDay="(//input[@placeholder='Join date'])[1]"
JoinDay_box="(//a[normalize-space()='Jan'])[1]"
Gender="//input[@placeholder='Gender']"
Gender_NAM="//span[normalize-space()='Male']"
Position="//input[@placeholder='Position']"
Position_DEV="//span[normalize-space()='Developer']"
Team="//input[@placeholder='Team']"
Team_Melon="//span[normalize-space()='Melon']"
Active_Account="//span[@class='el-switch__core']"
Search_row="//tr[contains(@class,'el-table__row')]"
Search_table="//tbody"
Search_value="Bình Nguyên"
OpenProfile_Successfully="Profile Open"