#Common
Searchbox_Assignments="xpath://input[contains(@placeholder,'Search')]"
From_Date="xpath:(//input[@placeholder='Pick a day'])[1]"
To_Date="xpath:(//input[@class='el-input__inner'])[3]"
Title_FindAssignments="//span[normalize-space()='Find assignment']"
Status_Title_FindAssignments="xpath://span[normalize-space()='Status']"
Checkbox_All="//span[@class='el-checkbox__input']//following-sibling::span[contains(text(),'All')]"
Checked_All_checkbutton="//span[contains(text(),'All')]//preceding-sibling::span[contains(@class,'el-checkbox__input')]//input[contains(@type,'checkbox')]"
Checkbox_INPROGRESS="//span[@class='el-checkbox__input']//following-sibling::span[contains(text(),'IN_PROGRESS')]"
Checked_INPROGRESS_checkbutton="//span[contains(text(),'IN_PROGRESS')]//preceding-sibling::span[contains(@class,'el-checkbox__input')]//input[contains(@type,'checkbox')]"
Checkbox_COMPLETE="//span[@class='el-checkbox__input']//following-sibling::span[contains(text(),'COMPLETED')]"
Checked_COMPLETE_checkbutton="//span[contains(text(),'COMPLETE')]//preceding-sibling::span[contains(@class,'el-checkbox__input')]//input[contains(@type,'checkbox')]"
Checkbox_OVERDUE="//span[@class='el-checkbox__input']//following-sibling::span[contains(text(),'OVERDUE')]"
Checked_OVERDUE_checkbutton="//span[contains(text(),'OVERDUE')]//preceding-sibling::span[contains(@class,'el-checkbox__input')]//input[contains(@type,'checkbox')]"
Checkbox_OPEN="//span[@class='el-checkbox__input']//following-sibling::span[contains(text(),'OPEN')]"
Checked_OPEN_checkbutton="//span[contains(text(),'OPEN')]//preceding-sibling::span[contains(@class,'el-checkbox__input')]//input[contains(@type,'checkbox')]"
Checkbox_LOCK="//span[@class='el-checkbox__input']//following-sibling::span[contains(text(),'LOCK')]"
Checked_LOCK_checkbutton="//span[contains(text(),'LOCK')]//preceding-sibling::span[contains(@class,'el-checkbox__input')]//input[contains(@type,'checkbox')]"

Table_Assignments="//tbody"
Data_picker_Assignments="//div[contains(@x-placement,'bottom-start')]"
page_pagination="//li[contains(@class,'number')]"
Prev_button="//button[@class='btn-prev']"
Next_button="//button[@class='btn-next']"
#NEW ASSIGNMENTS
New_assignments_Button="//button//child::span[contains(text(),'New')]"
Title_NewAssignments="//div[@class='el-message-box__title']//span[contains(text(),'New assignments')]"
Course_NewAssignments="(//input[@placeholder='Select'])[1]"
Course_Warning_NewAssignments="//div[normalize-space()='Please input course']"
Python_Tutorial_Course="//span[normalize-space()='The Python Tutorial']"
Trainee="//div[@class='el-select__tags']"
Who_Trainee="//li[contains(@class,'el-select')]//child::span[contains(text(),'hello')]"
Trainee_Warning_Assignments="//div[normalize-space()='Please input trainee']"
Trainee_NoDATA="//p[@class='el-select-dropdown__empty']"
Starttime_NewAssignments="//input[@placeholder='Pick a start date']"
Endtime_NewAssignments="//input[@placeholder='Pick a due date ']"
Ok_NewAssignments="//span[normalize-space()='OK']"
Popup_Notification="xpath://div[@role='alert']"
#Detail Progress
Info_suffix_button="]//i[contains(@class,'el-icon-info')]"
DetailProgress_Title_Assignments="//span[contains(text(),'Detail progress')]"
Infor_bar="//div[contains(@role,'treeitem')]"
CloseButton_DetailProgress="//i[contains(@class,'el-dialog__close el-icon el-icon-close')]"
#Delete Assignments
Delete_suffix_Button="]//i[contains(@class,'el-icon-delete')]"
ConfirmNO_Delete_button="//div[contains(@aria-hidden,'false')]//button[1]"
Confirm_Delete_button="//div[contains(@aria-hidden,'false')]//button[2]"
Delete_popup_DeleteAssignments="//div[contains(@class,'el-popconfirm')]"
#Edit Assignment
Title_EditAssignments="//span[normalize-space()='Edit assignments']"
Edit_suffix_Button="]//i[contains(@class,'el-icon-edit')]"
Starttime_EditAssignments="//input[contains(@placeholder,'Pick a date begin')]"
Endtime_EditAssignments="//input[@placeholder='Pick a due date ']"
Ok_EditAssignments="//span[normalize-space()='OK']"
Course_EditAssignments="(//input[contains(@disabled,'disabled')])[1]"
Trainee_EditAssignments="(//input[contains(@disabled,'disabled')])[2]"
CloseButton_EditAssignments="//i[@class='el-message-box__close el-icon-close']"